"""
AutoLoop Render - Streamlit UI

Upload a short video, choose a target duration, and losslessly stream-loop
it via ffmpeg (-stream_loop -1 -c copy) into a long output file.
"""
import hashlib
import math
import os
import time
import uuid

from PIL import Image, ImageDraw
import streamlit as st

import core_engine as engine
import job_history
import watch_engine


def _fmt_time(s: float) -> str:
    m, sec = divmod(abs(s), 60)
    return f"{int(m)}:{sec:04.1f}"


def _video_mime(path: str) -> str:
    return {".mov": "video/quicktime", ".mp4": "video/mp4"}.get(
        os.path.splitext(path)[1].lower(), "video/mp4"
    )


def _waveform_section(audio_path: str, audio_duration: float, loop_interval: float) -> None:
    """
    Show a waveform PNG (generated by FFmpeg once, then cached) with red vertical
    markers at every video-loop boundary, so the user can see where the music beat
    falls relative to each loop point.
    """
    wv_id = os.path.splitext(os.path.basename(audio_path))[0]
    wv_png = os.path.join(UPLOAD_DIR, f"wv_{wv_id}.png")

    if not os.path.exists(wv_png):
        with st.spinner("Generating waveform…"):
            try:
                engine.generate_waveform_png(audio_path, wv_png)
            except engine.AutoLoopError as exc:
                st.warning(f"Waveform unavailable: {exc}")
                return

    try:
        img = Image.open(wv_png).convert("RGBA")
    except Exception as exc:
        st.warning(f"Could not open waveform image: {exc}")
        return

    w, h = img.size
    overlay = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)

    n_loops = int(audio_duration / loop_interval) if loop_interval > 0 else 0
    px_per_loop = w * loop_interval / audio_duration if audio_duration > 0 else w
    # Skip markers that would overlap — enforce ≥ 20px gap between lines
    step = max(1, math.ceil(20 / px_per_loop))
    show_labels = px_per_loop >= 50

    for i in range(step, n_loops + 1, step):
        t = i * loop_interval
        if t > audio_duration + 0.001:
            break
        x = max(1, min(w - 2, int(t / audio_duration * (w - 1))))
        draw.line([(x, 0), (x, h)], fill=(255, 80, 80, 210), width=2)
        if show_labels:
            m_t, s_t = divmod(t, 60)
            draw.text((x + 3, 3), f"{int(m_t)}:{s_t:04.1f}", fill=(255, 210, 210, 220))

    result = Image.alpha_composite(img, overlay).convert("RGB")
    st.image(result, use_container_width=True)

    n_full = int(audio_duration / loop_interval) if loop_interval > 0 else 0
    tail = audio_duration - n_full * loop_interval
    tail_str = f" + {tail:.2f}s tail" if tail > 0.05 else ""
    st.caption(
        f"↻ = video restarts every **{loop_interval:.2f}s**  ·  "
        f"**{n_full}** full cycle(s){tail_str} within this audio track"
    )

UPLOAD_DIR = "uploads"
OUTPUT_DIR = "outputs"
LARGE_OUTPUT_WARN_BYTES = 20 * 1024**3       # 20 GB: ask for explicit confirmation
BROWSER_DOWNLOAD_LIMIT_BYTES = 1 * 1024**3   # 1 GB: above this, don't try to push bytes through the browser

st.set_page_config(page_title="AutoLoop Render", page_icon="🔁", layout="centered")
st.title("🔁 AutoLoop Render")
st.caption("Losslessly loop a short video to any target duration using FFmpeg stream copy.")

os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# --- ffmpeg/ffprobe availability check -------------------------------------------------
try:
    engine.get_ffmpeg_path()
    engine.get_ffprobe_path()
except engine.FFmpegNotFoundError as e:
    st.error(str(e))
    st.stop()

# ── Top-level tabs ──────────────────────────────────────────────────────────────────────
tab_single, tab_matrix, tab_watch, tab_history = st.tabs(
    ["Single clip", "Matrix render (N×M)", "Watch folder", "History"]
)


# ══════════════════════════════════════════════════════════════════════════════════════════
# TAB 1 — Single clip (existing flow)
# ══════════════════════════════════════════════════════════════════════════════════════════
with tab_single:

    # --- 1. Upload ---------------------------------------------------------------------------
    st.subheader("1. Upload a short video")
    uploaded_file = st.file_uploader(
        "MP4, MOV, MKV, AVI, or WEBM",
        type=[ext.lstrip(".") for ext in sorted(engine.ALLOWED_EXTENSIONS)],
    )

    video_info = None
    input_path = None
    effective_video_path = None
    effective_video_info = None
    trim_enabled = False
    boomerang_enabled = False
    crossfade_enabled = False

    if uploaded_file is not None:
        try:
            ext = engine.validate_extension(uploaded_file.name)
        except engine.InvalidVideoError as e:
            st.error(str(e))
            st.stop()

        # Persist with a random filename to avoid path traversal / collisions.
        if "upload_token" not in st.session_state or st.session_state.get("last_upload_name") != uploaded_file.name:
            st.session_state["upload_token"] = uuid.uuid4().hex[:10]
            st.session_state["last_upload_name"] = uploaded_file.name

        input_path = os.path.join(UPLOAD_DIR, f"{st.session_state['upload_token']}{ext}")
        if not os.path.exists(input_path):
            with open(input_path, "wb") as f:
                f.write(uploaded_file.getbuffer())

        try:
            video_info = engine.probe_video(input_path)
        except engine.InvalidVideoError as e:
            st.error(str(e))
            st.stop()

        col1, col2, col3 = st.columns(3)
        col1.metric("Source duration", f"{video_info.duration_seconds:.2f}s")
        col2.metric("Resolution", f"{video_info.width}x{video_info.height}")
        col3.metric("Codec", video_info.video_codec or "unknown")
        st.video(input_path)

        # Pipeline base — updated by each enabled pre-process step below
        effective_video_path = input_path
        effective_video_info = video_info

        # --- 1a. Trim in/out points --------------------------------------------------------
        st.divider()
        trim_enabled = st.checkbox(
            "✂️ Trim in/out points — select which portion of the source clip to loop",
            help=(
                "Frame-accurate trim via the FFmpeg trim filter (re-encodes the short segment once). "
                "Applied first in the pipeline, before Boomerang and Crossfade."
            ),
        )

        if trim_enabled:
            _dur = video_info.duration_seconds
            _step = 0.1 if _dur <= 60 else 0.5
            _max_v = float(int(_dur / _step) * _step)
            trim_range = st.slider(
                "Clip range",
                min_value=0.0, max_value=_max_v,
                value=(0.0, _max_v),
                step=_step, format="%.1fs",
            )
            trim_start, trim_end = float(trim_range[0]), float(trim_range[1])
            seg_dur = trim_end - trim_start

            if seg_dur < 0.5:
                st.error(f"Segment too short ({seg_dur:.1f}s) — minimum 0.5s.")
                st.stop()

            c1, c2, c3 = st.columns(3)
            c1.metric("In", _fmt_time(trim_start))
            c2.metric("Out", _fmt_time(trim_end))
            c3.metric("Segment", f"{seg_dur:.1f}s")

            _tr_id = f"tr_{st.session_state['upload_token']}_{int(trim_start * 10)}_{int(trim_end * 10)}"
            _tr_path = os.path.join(UPLOAD_DIR, f"{_tr_id}.mp4")

            if _tr_id not in st.session_state or not os.path.exists(_tr_path):
                with st.spinner(f"Trimming {_fmt_time(trim_start)} → {_fmt_time(trim_end)}…"):
                    try:
                        engine.create_trim_unit(
                            input_path, _tr_path, trim_start, trim_end,
                            has_audio=video_info.has_audio,
                        )
                        st.session_state[_tr_id] = _tr_path
                    except engine.AutoLoopError as e:
                        st.error(str(e))
                        st.stop()

            try:
                effective_video_info = engine.probe_video(_tr_path)
                effective_video_path = _tr_path
            except engine.InvalidVideoError as e:
                st.error(f"Trim unit corrupted — re-upload the source clip. ({e})")
                st.stop()

            _audio_note = " · audio preserved" if effective_video_info.has_audio else " · no audio in source"
            st.success(
                f"Trimmed to **{effective_video_info.duration_seconds:.2f}s** "
                f"({_fmt_time(trim_start)} → {_fmt_time(trim_end)}{_audio_note})."
            )

        # --- 1b. Boomerang option -----------------------------------------------------------
        st.divider()
        boomerang_enabled = st.checkbox(
            "🔁 Boomerang mode — create a seamless A→B→A→B loop by appending the reversed clip",
            help=(
                "Builds an A + reverse(A) unit (re-encodes once), "
                "then stream-copies that unit to fill the target duration."
            ),
        )

        if boomerang_enabled:
            if effective_video_info.duration_seconds > 60:
                st.warning(
                    f"Effective clip is {effective_video_info.duration_seconds:.0f}s — FFmpeg's `reverse` filter "
                    "buffers all decoded frames in RAM. Use Trim above to shorten it first."
                )

            quality_label = st.select_slider(
                "Boomerang unit quality",
                options=["Draft (CRF 28)", "Standard (CRF 23)", "High (CRF 18)"],
                value="High (CRF 18)",
            )
            crf_map = {"Draft (CRF 28)": 28, "Standard (CRF 23)": 23, "High (CRF 18)": 18}
            boomerang_crf = crf_map[quality_label]

            _evp_id = os.path.splitext(os.path.basename(effective_video_path))[0]
            bkey = f"bm_{_evp_id}_{boomerang_crf}"
            boomerang_unit_path = os.path.join(UPLOAD_DIR, f"bm_{_evp_id}_{boomerang_crf}.mp4")

            if bkey not in st.session_state or not os.path.exists(boomerang_unit_path):
                with st.spinner(f"Building boomerang unit (A + reverse(A)) at CRF {boomerang_crf}…"):
                    try:
                        engine.create_boomerang_unit(effective_video_path, boomerang_unit_path, crf=boomerang_crf)
                        st.session_state[bkey] = boomerang_unit_path
                    except engine.AutoLoopError as e:
                        st.error(str(e))
                        st.stop()

            try:
                effective_video_info = engine.probe_video(boomerang_unit_path)
                effective_video_path = boomerang_unit_path
            except engine.InvalidVideoError as e:
                st.error(f"Boomerang unit corrupted — re-upload the source clip. ({e})")
                st.stop()

            _half = effective_video_info.duration_seconds / 2
            st.success(
                f"Boomerang unit ready: **{effective_video_info.duration_seconds:.2f}s** "
                f"({_half:.2f}s forward + {_half:.2f}s reversed). "
                "Audio stripped — add music via **Match accompanying audio file(s)** below."
            )

        # --- 1c. Crossfade at loop junction -----------------------------------------------
        st.divider()
        _max_fade = (effective_video_info.duration_seconds - 0.5) / 2.0
        _can_crossfade = _max_fade >= 0.1

        crossfade_enabled = st.checkbox(
            "✨ Crossfade at loop junction — dissolve the end of each cycle into its own start",
            disabled=not _can_crossfade,
            help=(
                "Blends clip[end] fading out over clip[start] fading in at every loop boundary. "
                "Re-encodes the loop unit once, then stream-copies to fill duration."
            ),
        )

        if not _can_crossfade:
            st.caption(
                f"Clip too short for crossfade — need at least ~0.7s "
                f"(current effective length: {effective_video_info.duration_seconds:.2f}s)."
            )
        elif crossfade_enabled:
            _fade_max = float(round(min(_max_fade, 3.0), 1))
            _fade_default = float(round(min(0.5, _fade_max), 1))
            fade_duration = st.slider(
                "Fade duration",
                min_value=0.1, max_value=_fade_max,
                value=_fade_default, step=0.1, format="%.1fs",
                help=f"Each loop junction dissolves over this many seconds. Max: {_fade_max:.1f}s.",
            )

            _evp_id = os.path.splitext(os.path.basename(effective_video_path))[0]
            _cf_key = f"cf_{_evp_id}_{int(fade_duration * 1000)}"
            _cf_path = os.path.join(UPLOAD_DIR, f"cf_{_evp_id}_{int(fade_duration * 1000)}ms.mp4")

            if _cf_key not in st.session_state or not os.path.exists(_cf_path):
                with st.spinner(f"Building crossfade unit ({fade_duration:.1f}s fade)…"):
                    try:
                        engine.create_crossfade_unit(effective_video_path, _cf_path, fade_duration)
                        st.session_state[_cf_key] = _cf_path
                    except engine.AutoLoopError as e:
                        st.error(str(e))
                        st.stop()

            _pre_cf_dur = effective_video_info.duration_seconds
            try:
                effective_video_info = engine.probe_video(_cf_path)
                effective_video_path = _cf_path
            except engine.InvalidVideoError as e:
                st.error(f"Crossfade unit corrupted — re-upload the source clip. ({e})")
                st.stop()

            st.success(
                f"Crossfade unit ready: **{effective_video_info.duration_seconds:.2f}s** "
                f"(was {_pre_cf_dur:.2f}s · {fade_duration:.1f}s dissolve baked in at every junction). "
                "Audio stripped — add music via **Match accompanying audio file(s)** below."
            )

    # --- 1d. Loop junction preview -------------------------------------------------------
    st.divider()
    if effective_video_info is not None:
        _pv_max_window = min(5.0, effective_video_info.duration_seconds / 2 - 0.05)
    else:
        _pv_max_window = 0.0
    _pv_available = effective_video_path is not None and _pv_max_window >= 0.1

    preview_enabled = st.checkbox(
        "🔍 Preview loop junction",
        disabled=not _pv_available,
        help=(
            "Renders a short clip (last Ns → first Ns) so you can see exactly "
            "what the loop boundary looks like before committing to a full render."
        ),
    )
    if effective_video_info is not None and not _pv_available:
        st.caption(
            f"Clip too short for junction preview "
            f"(effective duration {effective_video_info.duration_seconds:.2f}s — need > 0.3s)."
        )
    elif effective_video_path is not None and preview_enabled:
        _pv_window = st.slider(
            "Window per side",
            min_value=0.1, max_value=_pv_max_window,
            value=min(2.0, _pv_max_window),
            step=0.1, format="%.1fs",
            help="Seconds taken from the end and the start of the clip.",
        )

        _pv_evp_id = os.path.splitext(os.path.basename(effective_video_path))[0]
        _pv_key = f"pv_{_pv_evp_id}_{int(_pv_window * 10)}"
        _pv_path = os.path.join(UPLOAD_DIR, f"{_pv_key}.mp4")

        if _pv_key not in st.session_state or not os.path.exists(_pv_path):
            with st.spinner(f"Building preview ({_pv_window:.1f}s tail + {_pv_window:.1f}s head)…"):
                try:
                    engine.create_junction_preview(
                        effective_video_path, _pv_path,
                        effective_video_info.duration_seconds, _pv_window,
                    )
                    st.session_state[_pv_key] = _pv_path
                except engine.AutoLoopError as e:
                    st.error(str(e))
                    st.stop()

        total_pv = _pv_window * 2
        st.caption(
            f"Last **{_pv_window:.1f}s** → First **{_pv_window:.1f}s** "
            f"({total_pv:.1f}s preview · the cut in the middle is the loop point)"
        )
        st.video(_pv_path)

    # --- 1e. Aspect ratio ----------------------------------------------------------------
    st.divider()
    ar_id = st.radio(
        "Output aspect ratio",
        options=list(engine.ASPECT_RATIOS.keys()),
        format_func=lambda x: engine.ASPECT_RATIOS[x].label,
        horizontal=True,
        key="ar_preset",
    )
    st.caption(engine.ASPECT_RATIOS[ar_id].description)

    if effective_video_path is not None and ar_id != "source":
        if effective_video_info.width and effective_video_info.height:
            _out_w, _out_h = engine.compute_crop_dims(
                effective_video_info.width, effective_video_info.height, ar_id
            )
            st.caption(
                f"Center crop: **{effective_video_info.width}×{effective_video_info.height}** "
                f"→ **{_out_w}×{_out_h}**"
            )

        _evp_id = os.path.splitext(os.path.basename(effective_video_path))[0]
        _ar_key = f"ar_{ar_id.replace(':', '_')}_{_evp_id}"
        _ar_path = os.path.join(UPLOAD_DIR, f"{_ar_key}.mp4")

        if _ar_key not in st.session_state or not os.path.exists(_ar_path):
            with st.spinner(f"Cropping to {ar_id}…"):
                try:
                    engine.create_aspect_ratio_unit(effective_video_path, _ar_path, ar_id)
                    st.session_state[_ar_key] = _ar_path
                except engine.AutoLoopError as e:
                    st.error(str(e))
                    st.stop()

        try:
            effective_video_info = engine.probe_video(_ar_path)
            effective_video_path = _ar_path
        except engine.InvalidVideoError as e:
            st.error(f"Aspect ratio unit corrupted — re-upload the source clip. ({e})")
            st.stop()

        st.success(
            f"Cropped to **{ar_id}** · {effective_video_info.width}×{effective_video_info.height} "
            "— add music below to restore audio."
        )

    # --- 1f. Burn-in overlay -------------------------------------------------------------
    st.divider()
    # Defaults (used when checkbox is off or variables would be undefined)
    wm_text = ""
    wm_text_pos = "bottom_right"
    wm_text_size = 36
    wm_text_color = "#FFFFFF"
    wm_text_opacity = 0.9
    wm_text_box = True
    wm_box_color = "#000000"
    wm_box_opacity = 0.4
    wm_logo_saved_path = None
    wm_logo_pos = "top_right"
    wm_logo_width = 15
    wm_logo_opacity = 0.9
    wm_margin = 20

    wm_enabled = st.checkbox(
        "🔖 Burn-in overlay — embed text or logo into every frame",
        help="Applied to the short loop unit before looping, so re-encoding is fast.",
        key="wm_enabled",
    )

    if wm_enabled:
        _wm_positions = list(engine.OVERLAY_POSITIONS.keys())
        _wm_tab_text, _wm_tab_logo = st.tabs(["📝 Text", "🖼 Logo"])

        with _wm_tab_text:
            wm_text = st.text_input(
                "Text content", placeholder="Channel Name · © 2025", key="wm_text"
            )
            _wmt_pc, _wmt_sc = st.columns(2)
            wm_text_pos = _wmt_pc.selectbox(
                "Position", options=_wm_positions,
                format_func=lambda x: engine.OVERLAY_POSITIONS[x],
                index=_wm_positions.index("bottom_right"), key="wm_text_pos",
            )
            wm_text_size = _wmt_sc.slider("Font size (px)", 12, 120, 36, step=4, key="wm_text_size")
            _wmt_cc, _wmt_oc = st.columns(2)
            wm_text_color = _wmt_cc.color_picker("Text color", "#FFFFFF", key="wm_text_color")
            wm_text_opacity = _wmt_oc.slider(
                "Text opacity", 0.1, 1.0, 0.9, step=0.05, key="wm_text_opacity"
            )
            wm_text_box = st.checkbox("Background box", value=True, key="wm_text_box")
            if wm_text_box:
                _wmt_bcc, _wmt_boc = st.columns(2)
                wm_box_color = _wmt_bcc.color_picker("Box color", "#000000", key="wm_box_color")
                wm_box_opacity = _wmt_boc.slider(
                    "Box opacity", 0.1, 1.0, 0.4, step=0.05, key="wm_box_opacity"
                )

        with _wm_tab_logo:
            wm_logo_file = st.file_uploader(
                "Logo / watermark image (PNG recommended for transparency)",
                type=["png", "jpg", "jpeg", "webp"],
                key="wm_logo_uploader",
            )
            if wm_logo_file is not None:
                if "wm_logo_tokens" not in st.session_state:
                    st.session_state["wm_logo_tokens"] = {}
                _wm_logo_tk = f"{wm_logo_file.name}:{wm_logo_file.size}"
                if _wm_logo_tk not in st.session_state["wm_logo_tokens"]:
                    st.session_state["wm_logo_tokens"][_wm_logo_tk] = uuid.uuid4().hex[:10]
                _wm_logo_ext = os.path.splitext(wm_logo_file.name)[1].lower()
                wm_logo_saved_path = os.path.join(
                    UPLOAD_DIR,
                    f"wml_{st.session_state['wm_logo_tokens'][_wm_logo_tk]}{_wm_logo_ext}",
                )
                if not os.path.exists(wm_logo_saved_path):
                    with open(wm_logo_saved_path, "wb") as _f:
                        _f.write(wm_logo_file.getbuffer())
            _wml_pc, _wml_sc = st.columns(2)
            wm_logo_pos = _wml_pc.selectbox(
                "Position", options=_wm_positions,
                format_func=lambda x: engine.OVERLAY_POSITIONS[x],
                index=_wm_positions.index("top_right"), key="wm_logo_pos",
            )
            wm_logo_width = _wml_sc.slider(
                "Logo width (% of frame)", 5, 50, 15, step=5, key="wm_logo_width"
            )
            wm_logo_opacity = st.slider(
                "Logo opacity", 0.1, 1.0, 0.9, step=0.05, key="wm_logo_opacity"
            )

        wm_margin = st.slider("Edge margin (px)", 0, 60, 20, step=4, key="wm_margin")

    _wm_cfg = engine.WatermarkConfig(
        text=wm_text,
        text_position=wm_text_pos,
        text_size=wm_text_size,
        text_color=wm_text_color,
        text_opacity=wm_text_opacity,
        text_box=wm_text_box,
        text_box_color=wm_box_color,
        text_box_opacity=wm_box_opacity,
        logo_path=wm_logo_saved_path,
        logo_position=wm_logo_pos,
        logo_width_pct=wm_logo_width,
        logo_opacity=wm_logo_opacity,
        margin=wm_margin,
    )

    if effective_video_path is not None and _wm_cfg.is_active:
        _evp_id = os.path.splitext(os.path.basename(effective_video_path))[0]
        _wm_hash = hashlib.md5("|".join([
            wm_text, wm_text_pos, str(wm_text_size), wm_text_color,
            str(wm_text_opacity), str(wm_text_box), wm_box_color, str(wm_box_opacity),
            wm_logo_saved_path or "", wm_logo_pos,
            str(wm_logo_width), str(wm_logo_opacity), str(wm_margin),
            _evp_id,
        ]).encode()).hexdigest()[:12]
        _wm_key = f"wm_{_wm_hash}"
        _wm_path = os.path.join(UPLOAD_DIR, f"{_wm_key}.mp4")

        if _wm_key not in st.session_state or not os.path.exists(_wm_path):
            with st.spinner("Burning in overlay…"):
                try:
                    engine.create_watermark_unit(effective_video_path, _wm_path, _wm_cfg)
                    st.session_state[_wm_key] = _wm_path
                except engine.AutoLoopError as e:
                    st.error(str(e))
                    st.stop()

        try:
            effective_video_info = engine.probe_video(_wm_path)
            effective_video_path = _wm_path
        except engine.InvalidVideoError as e:
            st.error(f"Watermark unit corrupted — re-upload the source clip. ({e})")
            st.stop()

        _wm_parts = []
        if wm_text.strip():
            _wm_parts.append(f'text "{wm_text[:28]}"')
        if wm_logo_saved_path:
            _wm_parts.append("logo")
        st.success(f"Overlay burned in: {' + '.join(_wm_parts)}")

    # --- 1g. Output format preset -------------------------------------------------------
    st.divider()
    enc_preset_id = st.radio(
        "Output format",
        options=list(engine.ENCODE_PRESETS.keys()),
        format_func=lambda x: engine.ENCODE_PRESETS[x].label,
        horizontal=True,
        key="enc_preset",
    )
    sel_preset = engine.ENCODE_PRESETS[enc_preset_id]

    _ep_c1, _ep_c2, _ep_c3 = st.columns(3)
    _ep_c1.metric("Encode speed", sel_preset.speed_label)
    _ep_c2.metric("File size", sel_preset.size_label)
    _ep_c3.metric("Compatibility", sel_preset.compat_label)
    st.caption(sel_preset.description)

    enc_crf: int | None = None
    if enc_preset_id == "h264":
        _h264_ql = st.select_slider(
            "H.264 quality",
            options=["Smaller file (CRF 28)", "Balanced (CRF 23)", "High quality (CRF 18)"],
            value="Balanced (CRF 23)",
            key="enc_crf_h264",
        )
        enc_crf = {"Smaller file (CRF 28)": 28, "Balanced (CRF 23)": 23, "High quality (CRF 18)": 18}[_h264_ql]
    elif enc_preset_id == "h265":
        _h265_ql = st.select_slider(
            "H.265 quality",
            options=["Smaller file (CRF 32)", "Balanced (CRF 28)", "High quality (CRF 24)"],
            value="Balanced (CRF 28)",
            key="enc_crf_h265",
        )
        enc_crf = {"Smaller file (CRF 32)": 32, "Balanced (CRF 28)": 28, "High quality (CRF 24)": 24}[_h265_ql]

    if effective_video_path is not None and enc_preset_id != "copy":
        _evp_id = os.path.splitext(os.path.basename(effective_video_path))[0]
        _enc_crf_str = str(enc_crf) if enc_crf is not None else "default"
        _enc_key = f"enc_{enc_preset_id}_{_enc_crf_str}_{_evp_id}"
        _enc_path = os.path.join(UPLOAD_DIR, f"{_enc_key}{sel_preset.ext}")
        if _enc_key not in st.session_state or not os.path.exists(_enc_path):
            with st.spinner(f"Re-encoding loop unit to {sel_preset.label}…"):
                try:
                    engine.create_encode_unit(effective_video_path, _enc_path, enc_preset_id, enc_crf)
                    st.session_state[_enc_key] = _enc_path
                except engine.AutoLoopError as e:
                    st.error(str(e))
                    st.stop()
        try:
            effective_video_info = engine.probe_video(_enc_path)
            effective_video_path = _enc_path
        except engine.InvalidVideoError as e:
            st.error(f"Encode unit corrupted — re-upload the source clip. ({e})")
            st.stop()
        if enc_preset_id != "prores":
            st.success(f"Loop unit re-encoded: **{sel_preset.label}** — audio stripped, add music below if needed.")
        else:
            st.success(f"Loop unit re-encoded: **{sel_preset.label}** · output will be .mov")

    # --- 2. Duration ------------------------------------------------------------------------
    st.subheader("2. Target output duration")
    duration_mode = st.radio(
        "How should the output duration be decided?",
        ["Set manually (H/M/S)", "Match accompanying audio file(s)"],
        horizontal=True,
    )

    # manual_target_seconds: single int, used only in manual mode.
    # audio_batch: list[engine.AudioBatchItem], used only in audio mode (1+ files = batch).
    manual_target_seconds = None
    manual_audio_path = None  # background music for manual mode (loops independently)
    duration_error = None
    audio_batch: list = []

    if duration_mode == "Set manually (H/M/S)":
        d1, d2, d3 = st.columns(3)
        hours = d1.number_input("Hours", min_value=0, max_value=engine.MAX_TARGET_HOURS, value=10, step=1)
        minutes = d2.number_input("Minutes", min_value=0, max_value=59, value=0, step=1)
        seconds = d3.number_input("Seconds", min_value=0, max_value=59, value=0, step=1)

        try:
            manual_target_seconds = engine.compute_total_seconds(hours, minutes, seconds)
        except engine.InvalidDurationError as e:
            duration_error = str(e)

        st.caption("Background music — optional. Audio loops independently alongside the video loop.")
        bg_audio_file = st.file_uploader(
            "Background music (optional)",
            type=[ext.lstrip(".") for ext in sorted(engine.ALLOWED_AUDIO_EXTENSIONS)],
            key="bg_audio_uploader",
        )

        if bg_audio_file is not None:
            try:
                bg_audio_ext = engine.validate_audio_extension(bg_audio_file.name)

                if "bg_audio_tokens" not in st.session_state:
                    st.session_state["bg_audio_tokens"] = {}
                bg_token_key = f"{bg_audio_file.name}:{bg_audio_file.size}"
                if bg_token_key not in st.session_state["bg_audio_tokens"]:
                    st.session_state["bg_audio_tokens"][bg_token_key] = uuid.uuid4().hex[:10]
                bg_token = st.session_state["bg_audio_tokens"][bg_token_key]

                bg_audio_path = os.path.join(UPLOAD_DIR, f"bg_{bg_token}{bg_audio_ext}")
                if not os.path.exists(bg_audio_path):
                    os.makedirs(UPLOAD_DIR, exist_ok=True)
                    with open(bg_audio_path, "wb") as f:
                        f.write(bg_audio_file.getbuffer())

                bg_audio_info = engine.probe_audio(bg_audio_path)
                manual_audio_path = bg_audio_path

                if manual_target_seconds:
                    audio_loops = manual_target_seconds / bg_audio_info.duration_seconds
                    st.info(
                        f"**{bg_audio_file.name}** · {_fmt_time(bg_audio_info.duration_seconds)} "
                        f"({bg_audio_info.duration_seconds:.1f}s)  —  "
                        f"will loop **{audio_loops:.1f}×** to fill the target duration."
                    )
                if effective_video_info is not None:
                    _waveform_section(
                        bg_audio_path,
                        bg_audio_info.duration_seconds,
                        effective_video_info.duration_seconds,
                    )
            except engine.AutoLoopError as e:
                st.error(f"Background audio rejected: {e}")

    else:
        uploaded_audios = st.file_uploader(
            "MP3, WAV, M4A, AAC, FLAC, OGG, or WMA — pick one file for a single render, or "
            "several for a batch. Each output is looped/trimmed to exactly that file's length, "
            "with that audio replacing the source video's own soundtrack.",
            type=[ext.lstrip(".") for ext in sorted(engine.ALLOWED_AUDIO_EXTENSIONS)],
            accept_multiple_files=True,
            key="audio_uploader",
        )

        if "audio_tokens" not in st.session_state:
            st.session_state["audio_tokens"] = {}

        if uploaded_audios:
            rows = []
            for uf in uploaded_audios:
                try:
                    audio_ext = engine.validate_audio_extension(uf.name)
                except engine.InvalidAudioError as e:
                    rows.append({"File": uf.name, "Duration": "-", "Status": f"rejected: {e}"})
                    continue

                token_key = f"{uf.name}:{uf.size}"
                if token_key not in st.session_state["audio_tokens"]:
                    st.session_state["audio_tokens"][token_key] = uuid.uuid4().hex[:10]
                token = st.session_state["audio_tokens"][token_key]

                audio_path = os.path.join(UPLOAD_DIR, f"{token}{audio_ext}")
                if not os.path.exists(audio_path):
                    with open(audio_path, "wb") as f:
                        f.write(uf.getbuffer())

                try:
                    audio_info = engine.probe_audio(audio_path)
                    target = engine.validate_duration_seconds(audio_info.duration_seconds)
                    audio_batch.append(
                        engine.AudioBatchItem(
                            display_name=uf.name,
                            audio_path=audio_path,
                            audio_info=audio_info,
                            target_seconds=target,
                        )
                    )
                    rows.append({"File": uf.name, "Duration": f"{target:.2f}s", "Status": "ready"})
                except engine.AutoLoopError as e:
                    rows.append({"File": uf.name, "Duration": "-", "Status": f"rejected: {e}"})

            st.table(rows)
            if not audio_batch:
                duration_error = "None of the uploaded audio files were usable — fix or replace them above."
            elif effective_video_info is not None:
                _wv_item = audio_batch[0]
                if len(audio_batch) > 1:
                    _wv_name = st.selectbox(
                        "Waveform",
                        [x.display_name for x in audio_batch],
                        key="wv_track_sel",
                        label_visibility="collapsed",
                    )
                    _wv_item = next(x for x in audio_batch if x.display_name == _wv_name)
                _waveform_section(
                    _wv_item.audio_path,
                    _wv_item.audio_info.duration_seconds,
                    effective_video_info.duration_seconds,
                )
        else:
            duration_error = "Upload at least one audio file to use as the duration source."

    if duration_error:
        st.warning(duration_error)

    # --- 2b. Audio settings (volume + fade) — shown only when output will have audio ----------
    _has_audio_output = (
        (duration_mode == "Set manually (H/M/S)" and manual_audio_path is not None)
        or (duration_mode != "Set manually (H/M/S)" and bool(audio_batch))
    )

    audio_volume = 1.0
    audio_fade_in = 0.0
    audio_fade_out = 0.0

    if _has_audio_output:
        with st.expander("🔊 Audio settings", expanded=False):
            audio_volume = st.slider(
                "Volume", min_value=0, max_value=200, value=100, step=5, format="%d%%"
            ) / 100.0

            fa_col, fo_col = st.columns(2)
            audio_fade_in = fa_col.slider(
                "Fade-in", min_value=0.0, max_value=60.0, value=0.0, step=0.5, format="%.1fs"
            )
            audio_fade_out = fo_col.slider(
                "Fade-out", min_value=0.0, max_value=60.0, value=0.0, step=0.5, format="%.1fs"
            )

            if audio_fade_in > 0 or audio_fade_out > 0:
                if duration_mode == "Set manually (H/M/S)" and manual_target_seconds:
                    if audio_fade_in + audio_fade_out >= manual_target_seconds:
                        st.warning(
                            f"Fade-in ({audio_fade_in:.1f}s) + Fade-out ({audio_fade_out:.1f}s) "
                            f"exceeds the target duration ({manual_target_seconds}s)."
                        )
                elif audio_batch:
                    shortest = min(item.target_seconds for item in audio_batch)
                    if audio_fade_in + audio_fade_out >= shortest:
                        st.warning(
                            f"Fade-in + Fade-out ({audio_fade_in + audio_fade_out:.1f}s total) "
                            f"exceeds the shortest audio track ({shortest:.1f}s). Reduce fade durations."
                        )

    # --- 3. Estimate & confirm ---------------------------------------------------------------
    # render_jobs: list of (label, target_seconds, audio_path_or_None, loop_audio_bool)
    # loop_audio=True  → render_looped_video_with_looped_audio (both streams loop)
    # loop_audio=False → render_looped_video_with_audio (audio plays once, target = audio duration)
    render_jobs = []
    if video_info is not None:
        if duration_mode == "Set manually (H/M/S)" and manual_target_seconds:
            render_jobs = [(uploaded_file.name, manual_target_seconds, manual_audio_path, True)]
        elif duration_mode != "Set manually (H/M/S)" and audio_batch:
            render_jobs = [
                (item.display_name, item.target_seconds, item.audio_path, False)
                for item in audio_batch
            ]

    proceed = False
    confirmed_large = True

    if render_jobs:
        total_estimated_bytes = sum(
            engine.estimate_output_size_bytes(effective_video_info, secs)
            + (int(24 * 1024 * secs) if ap else 0)  # 192 kbps AAC when audio is present
            for _, secs, ap, _ in render_jobs
        )
        if len(render_jobs) == 1:
            loop_count = render_jobs[0][1] / effective_video_info.duration_seconds
            if boomerang_enabled and crossfade_enabled:
                unit_desc, unit_label = "boomerang + crossfade unit", "boomerang+crossfade cycle"
            elif boomerang_enabled:
                unit_desc, unit_label = "boomerang unit", "boomerang cycle"
            elif crossfade_enabled:
                unit_desc, unit_label = "crossfade unit", "crossfade cycle"
            else:
                unit_desc, unit_label = "source", "loop"
            st.write(
                f"Will repeat the {unit_desc} **{loop_count:,.1f}x** ({unit_label}) "
                f"→ estimated output size **{engine.format_bytes(total_estimated_bytes)}**"
            )
        else:
            st.write(
                f"Batch of **{len(render_jobs)}** outputs → estimated total size "
                f"**{engine.format_bytes(total_estimated_bytes)}**"
            )

        try:
            engine.ensure_disk_space(OUTPUT_DIR, total_estimated_bytes)
            proceed = True
        except engine.InsufficientDiskSpaceError as e:
            st.error(str(e))
            proceed = False

        if proceed and total_estimated_bytes > LARGE_OUTPUT_WARN_BYTES:
            confirmed_large = st.checkbox(
                f"This will write roughly {engine.format_bytes(total_estimated_bytes)} to disk in total. "
                "I understand and want to proceed."
            )

    # --- 4. Render --------------------------------------------------------------------------
    st.subheader("3. Render")
    render_label = "Render Looped Video" if len(render_jobs) <= 1 else f"Render Batch ({len(render_jobs)} files)"
    render_clicked = st.button(
        render_label,
        disabled=not (render_jobs and proceed and confirmed_large),
        type="primary",
    )

    if render_clicked:
        results = []
        progress_bar = st.progress(0.0)
        status = st.empty()
        start = time.time()

        _out_ext = None if enc_preset_id == "copy" else sel_preset.ext
        if duration_mode == "Set manually (H/M/S)":
            label, secs, audio_p, loop_audio = render_jobs[0]
            status.write(f"Rendering: **{label}**")
            output_path = engine.build_output_path(OUTPUT_DIR, uploaded_file.name, output_ext=_out_ext)
            try:
                if audio_p is None:
                    engine.render_looped_video(effective_video_path, output_path, secs)
                else:
                    engine.render_looped_video_with_looped_audio(
                        effective_video_path, audio_p, output_path, secs,
                        volume=audio_volume, fade_in=audio_fade_in, fade_out=audio_fade_out,
                    )
                _sz = os.path.getsize(output_path)
                results.append({"label": label, "success": True, "path": output_path, "size": _sz})
                job_history.append_job(job_history.make_record(
                    label=label, source_file=uploaded_file.name, output_path=output_path,
                    duration_seconds=secs, size_bytes=_sz,
                    preset_id=enc_preset_id, ar_id=ar_id, tab="single",
                ))
            except engine.AutoLoopError as e:
                results.append({"label": label, "success": False, "error": str(e)})
            progress_bar.progress(1.0)
        else:
            for i, batch_result in enumerate(
                engine.render_audio_batch(
                    effective_video_path, uploaded_file.name, audio_batch, OUTPUT_DIR,
                    volume=audio_volume, fade_in=audio_fade_in, fade_out=audio_fade_out,
                    output_ext=_out_ext,
                )
            ):
                status.write(f"Rendering {i + 1}/{len(audio_batch)}: **{batch_result.display_name}**")
                if batch_result.success:
                    results.append({"label": batch_result.display_name, "success": True,
                                     "path": batch_result.output_path, "size": batch_result.size_bytes})
                    job_history.append_job(job_history.make_record(
                        label=batch_result.display_name, source_file=uploaded_file.name,
                        output_path=batch_result.output_path,
                        duration_seconds=audio_batch[i].target_seconds,
                        size_bytes=batch_result.size_bytes,
                        preset_id=enc_preset_id, ar_id=ar_id, tab="single",
                    ))
                else:
                    results.append({"label": batch_result.display_name, "success": False,
                                     "error": batch_result.error})
                progress_bar.progress((i + 1) / len(audio_batch))

        status.empty()
        elapsed = time.time() - start
        succeeded = [r for r in results if r["success"]]
        failed = [r for r in results if not r["success"]]

        if succeeded:
            total_size = sum(r["size"] for r in succeeded)
            st.success(
                f"Finished {len(succeeded)}/{len(results)} in {elapsed:.1f}s. "
                f"Total output: {engine.format_bytes(total_size)}"
            )
        if failed:
            st.error(f"{len(failed)} file(s) failed to render.")

        for r in results:
            if not r["success"]:
                st.write(f"❌ **{r['label']}** — {r['error']}")
                continue

            st.write(f"✅ **{r['label']}** — {engine.format_bytes(r['size'])}")
            st.code(os.path.abspath(r["path"]))
            if r["size"] <= BROWSER_DOWNLOAD_LIMIT_BYTES:
                with open(r["path"], "rb") as f:
                    st.download_button(
                        f"Download {os.path.basename(r['path'])}",
                        data=f,
                        file_name=os.path.basename(r["path"]),
                        mime=_video_mime(r["path"]),
                        key=f"dl_{r['path']}",
                    )
            else:
                st.info(
                    f"Exceeds the in-browser download limit ({engine.format_bytes(BROWSER_DOWNLOAD_LIMIT_BYTES)}). "
                    "Grab it directly from the path above."
                )


# ══════════════════════════════════════════════════════════════════════════════════════════
# TAB 2 — Matrix render (N videos × M audios)
# ══════════════════════════════════════════════════════════════════════════════════════════
with tab_matrix:
    st.caption(
        "Upload N short video clips and M audio tracks → render N×M combinations. "
        "Useful for exporting multiple versions across platforms (e.g. 3 music tracks × 5 visuals)."
    )

    # ── 1. Video clips ──────────────────────────────────────────────────────────────────
    st.subheader("1. Video clips")
    mx_video_uploads = st.file_uploader(
        "Upload one or more short video clips",
        type=[ext.lstrip(".") for ext in sorted(engine.ALLOWED_EXTENSIONS)],
        accept_multiple_files=True,
        key="mx_video_uploader",
    )

    if "mx_video_tokens" not in st.session_state:
        st.session_state["mx_video_tokens"] = {}

    mx_videos: list[engine.MatrixVideoItem] = []

    if mx_video_uploads:
        mx_video_rows = []
        for uf in mx_video_uploads:
            try:
                v_ext = engine.validate_extension(uf.name)
            except engine.InvalidVideoError as e:
                mx_video_rows.append({"Clip": uf.name, "Duration": "-", "Resolution": "-", "Status": f"rejected: {e}"})
                continue

            tk = f"{uf.name}:{uf.size}"
            if tk not in st.session_state["mx_video_tokens"]:
                st.session_state["mx_video_tokens"][tk] = uuid.uuid4().hex[:10]
            v_tok = st.session_state["mx_video_tokens"][tk]

            v_path = os.path.join(UPLOAD_DIR, f"mx_{v_tok}{v_ext}")
            if not os.path.exists(v_path):
                with open(v_path, "wb") as f:
                    f.write(uf.getbuffer())

            try:
                v_info = engine.probe_video(v_path)
                mx_videos.append(engine.MatrixVideoItem(
                    display_name=uf.name,
                    video_path=v_path,
                    video_info=v_info,
                ))
                res = f"{v_info.width}×{v_info.height}" if v_info.width else "?"
                mx_video_rows.append({
                    "Clip": uf.name,
                    "Duration": f"{_fmt_time(v_info.duration_seconds)} ({v_info.duration_seconds:.2f}s)",
                    "Resolution": res,
                    "Status": "ready",
                })
            except engine.InvalidVideoError as e:
                mx_video_rows.append({"Clip": uf.name, "Duration": "-", "Resolution": "-", "Status": f"rejected: {e}"})

        st.table(mx_video_rows)

    # ── 2. Audio tracks ──────────────────────────────────────────────────────────────────
    st.subheader("2. Audio tracks")
    mx_audio_uploads = st.file_uploader(
        "Upload one or more audio tracks",
        type=[ext.lstrip(".") for ext in sorted(engine.ALLOWED_AUDIO_EXTENSIONS)],
        accept_multiple_files=True,
        key="mx_audio_uploader",
    )

    if "mx_audio_tokens" not in st.session_state:
        st.session_state["mx_audio_tokens"] = {}

    mx_audios: list[engine.AudioBatchItem] = []

    if mx_audio_uploads:
        mx_audio_rows = []
        for uf in mx_audio_uploads:
            try:
                a_ext = engine.validate_audio_extension(uf.name)
            except engine.InvalidAudioError as e:
                mx_audio_rows.append({"Track": uf.name, "Duration": "-", "Status": f"rejected: {e}"})
                continue

            tk = f"{uf.name}:{uf.size}"
            if tk not in st.session_state["mx_audio_tokens"]:
                st.session_state["mx_audio_tokens"][tk] = uuid.uuid4().hex[:10]
            a_tok = st.session_state["mx_audio_tokens"][tk]

            a_path = os.path.join(UPLOAD_DIR, f"mxa_{a_tok}{a_ext}")
            if not os.path.exists(a_path):
                with open(a_path, "wb") as f:
                    f.write(uf.getbuffer())

            try:
                a_info = engine.probe_audio(a_path)
                a_target = engine.validate_duration_seconds(a_info.duration_seconds)
                mx_audios.append(engine.AudioBatchItem(
                    display_name=uf.name,
                    audio_path=a_path,
                    audio_info=a_info,
                    target_seconds=a_target,
                ))
                mx_audio_rows.append({
                    "Track": uf.name,
                    "Duration": f"{_fmt_time(a_info.duration_seconds)} ({a_info.duration_seconds:.1f}s)",
                    "Status": "ready",
                })
            except engine.AutoLoopError as e:
                mx_audio_rows.append({"Track": uf.name, "Duration": "-", "Status": f"rejected: {e}"})

        st.table(mx_audio_rows)

    # ── 3. Target duration ──────────────────────────────────────────────────────────────
    st.subheader("3. Target duration")
    mx_duration_mode = st.radio(
        "Duration per output",
        ["Match each audio track's duration", "Set manually (H/M/S) — audio also loops"],
        horizontal=True,
        key="mx_duration_mode",
    )

    mx_manual_seconds = None
    mx_duration_error = None

    if mx_duration_mode != "Match each audio track's duration":
        mx_d1, mx_d2, mx_d3 = st.columns(3)
        mx_hours = mx_d1.number_input("Hours", min_value=0, max_value=engine.MAX_TARGET_HOURS, value=1, step=1, key="mx_hours")
        mx_mins = mx_d2.number_input("Minutes", min_value=0, max_value=59, value=0, step=1, key="mx_minutes")
        mx_secs_val = mx_d3.number_input("Seconds", min_value=0, max_value=59, value=0, step=1, key="mx_secs")
        try:
            mx_manual_seconds = engine.compute_total_seconds(mx_hours, mx_mins, mx_secs_val)
        except engine.InvalidDurationError as e:
            mx_duration_error = str(e)
            st.warning(mx_duration_error)

    # ── 4. Audio settings ──────────────────────────────────────────────────────────────
    mx_volume = 1.0
    mx_fade_in = 0.0
    mx_fade_out = 0.0

    if mx_audios:
        with st.expander("🔊 Audio settings", expanded=False):
            mx_volume = st.slider(
                "Volume", min_value=0, max_value=200, value=100, step=5, format="%d%%", key="mx_vol"
            ) / 100.0
            mx_fa_col, mx_fo_col = st.columns(2)
            mx_fade_in = mx_fa_col.slider(
                "Fade-in", min_value=0.0, max_value=60.0, value=0.0, step=0.5, format="%.1fs", key="mx_fi"
            )
            mx_fade_out = mx_fo_col.slider(
                "Fade-out", min_value=0.0, max_value=60.0, value=0.0, step=0.5, format="%.1fs", key="mx_fo"
            )
            if mx_fade_in > 0 or mx_fade_out > 0:
                if mx_duration_mode != "Match each audio track's duration" and mx_manual_seconds:
                    if mx_fade_in + mx_fade_out >= mx_manual_seconds:
                        st.warning(f"Fade total ({mx_fade_in + mx_fade_out:.1f}s) exceeds target ({mx_manual_seconds}s).")
                elif mx_audios:
                    shortest = min(a.target_seconds for a in mx_audios)
                    if mx_fade_in + mx_fade_out >= shortest:
                        st.warning(f"Fade total exceeds shortest audio ({shortest:.1f}s). Reduce fade durations.")

    # ── 5. Aspect ratio ────────────────────────────────────────────────────────────────────
    mx_ar_id = st.radio(
        "Output aspect ratio",
        options=list(engine.ASPECT_RATIOS.keys()),
        format_func=lambda x: engine.ASPECT_RATIOS[x].label,
        horizontal=True,
        key="mx_ar_preset",
    )
    st.caption(engine.ASPECT_RATIOS[mx_ar_id].description)

    # ── 6. Burn-in overlay ─────────────────────────────────────────────────────────────────
    mx_wm_text = ""
    mx_wm_text_pos = "bottom_right"
    mx_wm_text_size = 36
    mx_wm_text_color = "#FFFFFF"
    mx_wm_text_opacity = 0.9
    mx_wm_text_box = True
    mx_wm_box_color = "#000000"
    mx_wm_box_opacity = 0.4
    mx_wm_logo_saved_path = None
    mx_wm_logo_pos = "top_right"
    mx_wm_logo_width = 15
    mx_wm_logo_opacity = 0.9
    mx_wm_margin = 20

    mx_wm_enabled = st.checkbox(
        "🔖 Burn-in overlay — embed text or logo into every frame",
        key="mx_wm_enabled",
    )

    if mx_wm_enabled:
        _mx_wm_positions = list(engine.OVERLAY_POSITIONS.keys())
        _mx_wm_tab_text, _mx_wm_tab_logo = st.tabs(["📝 Text", "🖼 Logo"])

        with _mx_wm_tab_text:
            mx_wm_text = st.text_input("Text content", placeholder="Channel Name · © 2025", key="mx_wm_text")
            _mxt_pc, _mxt_sc = st.columns(2)
            mx_wm_text_pos = _mxt_pc.selectbox(
                "Position", options=_mx_wm_positions,
                format_func=lambda x: engine.OVERLAY_POSITIONS[x],
                index=_mx_wm_positions.index("bottom_right"), key="mx_wm_text_pos",
            )
            mx_wm_text_size = _mxt_sc.slider("Font size (px)", 12, 120, 36, step=4, key="mx_wm_text_size")
            _mxt_cc, _mxt_oc = st.columns(2)
            mx_wm_text_color = _mxt_cc.color_picker("Text color", "#FFFFFF", key="mx_wm_text_color")
            mx_wm_text_opacity = _mxt_oc.slider("Text opacity", 0.1, 1.0, 0.9, step=0.05, key="mx_wm_text_opacity")
            mx_wm_text_box = st.checkbox("Background box", value=True, key="mx_wm_text_box")
            if mx_wm_text_box:
                _mxt_bcc, _mxt_boc = st.columns(2)
                mx_wm_box_color = _mxt_bcc.color_picker("Box color", "#000000", key="mx_wm_box_color")
                mx_wm_box_opacity = _mxt_boc.slider("Box opacity", 0.1, 1.0, 0.4, step=0.05, key="mx_wm_box_opacity")

        with _mx_wm_tab_logo:
            mx_wm_logo_file = st.file_uploader(
                "Logo / watermark image (PNG recommended)",
                type=["png", "jpg", "jpeg", "webp"], key="mx_wm_logo_uploader",
            )
            if mx_wm_logo_file is not None:
                if "mx_wm_logo_tokens" not in st.session_state:
                    st.session_state["mx_wm_logo_tokens"] = {}
                _mxwml_tk = f"{mx_wm_logo_file.name}:{mx_wm_logo_file.size}"
                if _mxwml_tk not in st.session_state["mx_wm_logo_tokens"]:
                    st.session_state["mx_wm_logo_tokens"][_mxwml_tk] = uuid.uuid4().hex[:10]
                _mxwml_ext = os.path.splitext(mx_wm_logo_file.name)[1].lower()
                mx_wm_logo_saved_path = os.path.join(
                    UPLOAD_DIR,
                    f"mxwml_{st.session_state['mx_wm_logo_tokens'][_mxwml_tk]}{_mxwml_ext}",
                )
                if not os.path.exists(mx_wm_logo_saved_path):
                    with open(mx_wm_logo_saved_path, "wb") as _f:
                        _f.write(mx_wm_logo_file.getbuffer())
            _mxl_pc, _mxl_sc = st.columns(2)
            mx_wm_logo_pos = _mxl_pc.selectbox(
                "Position", options=_mx_wm_positions,
                format_func=lambda x: engine.OVERLAY_POSITIONS[x],
                index=_mx_wm_positions.index("top_right"), key="mx_wm_logo_pos",
            )
            mx_wm_logo_width = _mxl_sc.slider("Logo width (% of frame)", 5, 50, 15, step=5, key="mx_wm_logo_width")
            mx_wm_logo_opacity = st.slider("Logo opacity", 0.1, 1.0, 0.9, step=0.05, key="mx_wm_logo_opacity")

        mx_wm_margin = st.slider("Edge margin (px)", 0, 60, 20, step=4, key="mx_wm_margin")

    _mx_wm_cfg = engine.WatermarkConfig(
        text=mx_wm_text, text_position=mx_wm_text_pos, text_size=mx_wm_text_size,
        text_color=mx_wm_text_color, text_opacity=mx_wm_text_opacity,
        text_box=mx_wm_text_box, text_box_color=mx_wm_box_color, text_box_opacity=mx_wm_box_opacity,
        logo_path=mx_wm_logo_saved_path, logo_position=mx_wm_logo_pos,
        logo_width_pct=mx_wm_logo_width, logo_opacity=mx_wm_logo_opacity, margin=mx_wm_margin,
    )

    # ── 7. Output format preset ────────────────────────────────────────────────────────────
    mx_preset_id = st.radio(
        "Output format",
        options=list(engine.ENCODE_PRESETS.keys()),
        format_func=lambda x: engine.ENCODE_PRESETS[x].label,
        horizontal=True,
        key="mx_enc_preset",
    )
    mx_sel_preset = engine.ENCODE_PRESETS[mx_preset_id]
    _mx_c1, _mx_c2, _mx_c3 = st.columns(3)
    _mx_c1.metric("Encode speed", mx_sel_preset.speed_label)
    _mx_c2.metric("File size", mx_sel_preset.size_label)
    _mx_c3.metric("Compatibility", mx_sel_preset.compat_label)
    st.caption(mx_sel_preset.description)

    mx_enc_crf: int | None = None
    if mx_preset_id == "h264":
        _mx_h264_ql = st.select_slider(
            "H.264 quality",
            options=["Smaller file (CRF 28)", "Balanced (CRF 23)", "High quality (CRF 18)"],
            value="Balanced (CRF 23)",
            key="mx_enc_crf_h264",
        )
        mx_enc_crf = {"Smaller file (CRF 28)": 28, "Balanced (CRF 23)": 23, "High quality (CRF 18)": 18}[_mx_h264_ql]
    elif mx_preset_id == "h265":
        _mx_h265_ql = st.select_slider(
            "H.265 quality",
            options=["Smaller file (CRF 32)", "Balanced (CRF 28)", "High quality (CRF 24)"],
            value="Balanced (CRF 28)",
            key="mx_enc_crf_h265",
        )
        mx_enc_crf = {"Smaller file (CRF 32)": 32, "Balanced (CRF 28)": 28, "High quality (CRF 24)": 24}[_mx_h265_ql]

    # ── Estimate & render ──────────────────────────────────────────────────────────────
    mx_total_jobs = len(mx_videos) * len(mx_audios)
    mx_use_looped = mx_duration_mode != "Match each audio track's duration"
    mx_ready = (
        bool(mx_videos)
        and bool(mx_audios)
        and not mx_duration_error
        and (not mx_use_looped or mx_manual_seconds)
    )

    mx_proceed = False
    mx_confirmed_large = True

    if mx_ready:
        mx_total_bytes = 0
        for vi in mx_videos:
            for ai in mx_audios:
                t = mx_manual_seconds if mx_use_looped else ai.target_seconds
                mx_total_bytes += engine.estimate_output_size_bytes(vi.video_info, t)
                mx_total_bytes += int(24 * 1024 * t)  # 192 kbps AAC overhead

        st.write(
            f"**{len(mx_videos)} clip(s) × {len(mx_audios)} track(s) = {mx_total_jobs} output files** "
            f"— estimated total **{engine.format_bytes(mx_total_bytes)}**"
        )

        try:
            engine.ensure_disk_space(OUTPUT_DIR, mx_total_bytes)
            mx_proceed = True
        except engine.InsufficientDiskSpaceError as e:
            st.error(str(e))

        if mx_proceed and mx_total_bytes > LARGE_OUTPUT_WARN_BYTES:
            mx_confirmed_large = st.checkbox(
                f"This will write ~{engine.format_bytes(mx_total_bytes)} to disk. I understand and want to proceed.",
                key="mx_large_confirm",
            )

    st.subheader("4. Render")
    _mx_existing = (
        [
            engine.build_matrix_output_path(OUTPUT_DIR, vi.display_name, ai.display_name,
                                             output_ext=None if mx_preset_id == "copy" else mx_sel_preset.ext)
            for vi in mx_videos for ai in mx_audios
        ]
        if mx_ready else []
    )
    _mx_n_existing = sum(1 for p in _mx_existing if os.path.exists(p))
    if _mx_n_existing:
        st.info(
            f"{_mx_n_existing}/{mx_total_jobs} output file(s) already exist in the output folder.",
            icon="ℹ️",
        )
    mx_skip_existing = st.checkbox(
        "Skip combos whose output file already exists (saves time on re-runs)",
        value=bool(_mx_n_existing),
        key="mx_skip_existing",
    )

    mx_btn_label = (
        f"Render {mx_total_jobs} files ({len(mx_videos)}×{len(mx_audios)})"
        if mx_total_jobs > 0 else "Render Matrix"
    )
    mx_render_clicked = st.button(
        mx_btn_label,
        disabled=not (mx_ready and mx_proceed and mx_confirmed_large),
        type="primary",
        key="mx_render_btn",
    )

    if mx_render_clicked:
        mx_results = []
        mx_progress = st.progress(0.0)
        mx_status = st.empty()
        mx_start = time.time()
        mx_done = 0
        _mx_out_ext = None if mx_preset_id == "copy" else mx_sel_preset.ext

        for vi in mx_videos:
            # Apply aspect ratio + encode preset once per video; reuse for all audio combos
            _mx_v_path = vi.video_path
            _mx_vi_id = os.path.splitext(os.path.basename(vi.video_path))[0]

            # Step A: aspect ratio crop
            if mx_ar_id != "source":
                _mx_ar_key = f"mxar_{mx_ar_id.replace(':', '_')}_{_mx_vi_id}"
                _mx_ar_path = os.path.join(UPLOAD_DIR, f"{_mx_ar_key}.mp4")
                if _mx_ar_key not in st.session_state or not os.path.exists(_mx_ar_path):
                    mx_status.write(f"Cropping **{vi.display_name}** to {mx_ar_id}…")
                    try:
                        engine.create_aspect_ratio_unit(_mx_v_path, _mx_ar_path, mx_ar_id)
                        st.session_state[_mx_ar_key] = _mx_ar_path
                    except engine.AutoLoopError as e:
                        mx_results.append({
                            "label": f"{vi.display_name} (crop)", "success": False, "error": str(e)
                        })
                        mx_done += len(mx_audios)
                        mx_progress.progress(mx_done / mx_total_jobs)
                        continue
                _mx_v_path = _mx_ar_path

            # Step B: watermark
            if _mx_wm_cfg.is_active:
                _mx_wm_stem = os.path.splitext(os.path.basename(_mx_v_path))[0]
                _mx_wm_hash_str = "|".join([
                    mx_wm_text, mx_wm_text_pos, str(mx_wm_text_size),
                    mx_wm_text_color, str(mx_wm_text_opacity), str(mx_wm_text_box),
                    mx_wm_box_color, str(mx_wm_box_opacity),
                    str(mx_wm_logo_saved_path), mx_wm_logo_pos,
                    str(mx_wm_logo_width), str(mx_wm_logo_opacity), str(mx_wm_margin),
                    _mx_wm_stem,
                ])
                _mx_wm_hash = hashlib.md5(_mx_wm_hash_str.encode()).hexdigest()[:12]
                _mx_wm_key = f"mxwm_{_mx_wm_hash}"
                _mx_wm_path = os.path.join(UPLOAD_DIR, f"{_mx_wm_key}.mp4")
                if _mx_wm_key not in st.session_state or not os.path.exists(_mx_wm_path):
                    mx_status.write(f"Burning overlay into **{vi.display_name}**…")
                    try:
                        engine.create_watermark_unit(_mx_v_path, _mx_wm_path, _mx_wm_cfg)
                        st.session_state[_mx_wm_key] = _mx_wm_path
                    except engine.AutoLoopError as e:
                        mx_results.append({
                            "label": f"{vi.display_name} (watermark)", "success": False, "error": str(e)
                        })
                        continue
                _mx_v_path = _mx_wm_path

            # Step C: encode preset
            if mx_preset_id != "copy":
                _mx_ar_stem = os.path.splitext(os.path.basename(_mx_v_path))[0]
                _mx_enc_crf_str = str(mx_enc_crf) if mx_enc_crf is not None else "default"
                _mx_enc_key = f"mxenc_{mx_preset_id}_{_mx_enc_crf_str}_{_mx_ar_stem}"
                _mx_enc_path = os.path.join(UPLOAD_DIR, f"{_mx_enc_key}{mx_sel_preset.ext}")
                if _mx_enc_key not in st.session_state or not os.path.exists(_mx_enc_path):
                    mx_status.write(f"Re-encoding **{vi.display_name}** to {mx_sel_preset.label}…")
                    try:
                        engine.create_encode_unit(_mx_v_path, _mx_enc_path, mx_preset_id, mx_enc_crf)
                        st.session_state[_mx_enc_key] = _mx_enc_path
                    except engine.AutoLoopError as e:
                        mx_results.append({
                            "label": f"{vi.display_name} (encode)", "success": False, "error": str(e)
                        })
                        mx_done += len(mx_audios)
                        mx_progress.progress(mx_done / mx_total_jobs)
                        continue
                _mx_v_path = _mx_enc_path

            for ai in mx_audios:
                combo_label = f"{vi.display_name} × {ai.display_name}"
                mx_status.write(f"({mx_done + 1}/{mx_total_jobs}) **{combo_label}**")

                t = mx_manual_seconds if mx_use_looped else ai.target_seconds
                out_path = engine.build_matrix_output_path(
                    OUTPUT_DIR, vi.display_name, ai.display_name, output_ext=_mx_out_ext
                )

                if mx_skip_existing and os.path.exists(out_path):
                    mx_results.append({
                        "label": combo_label, "success": True, "skipped": True,
                        "path": out_path, "size": os.path.getsize(out_path),
                    })
                    mx_done += 1
                    mx_progress.progress(mx_done / mx_total_jobs)
                    continue

                try:
                    if mx_use_looped:
                        engine.render_looped_video_with_looped_audio(
                            _mx_v_path, ai.audio_path, out_path, t,
                            volume=mx_volume, fade_in=mx_fade_in, fade_out=mx_fade_out,
                        )
                    else:
                        engine.render_looped_video_with_audio(
                            _mx_v_path, ai.audio_path, out_path, t,
                            volume=mx_volume, fade_in=mx_fade_in, fade_out=mx_fade_out,
                        )
                    _mx_sz = os.path.getsize(out_path)
                    mx_results.append({
                        "label": combo_label, "success": True,
                        "path": out_path, "size": _mx_sz,
                    })
                    job_history.append_job(job_history.make_record(
                        label=combo_label,
                        source_file=f"{vi.display_name} + {ai.display_name}",
                        output_path=out_path, duration_seconds=t, size_bytes=_mx_sz,
                        preset_id=mx_preset_id, ar_id=mx_ar_id, tab="matrix",
                    ))
                except engine.AutoLoopError as e:
                    mx_results.append({"label": combo_label, "success": False, "error": str(e)})

                mx_done += 1
                mx_progress.progress(mx_done / mx_total_jobs)

        mx_status.empty()
        mx_elapsed = time.time() - mx_start
        mx_succeeded = [r for r in mx_results if r["success"] and not r.get("skipped")]
        mx_skipped  = [r for r in mx_results if r.get("skipped")]
        mx_failed   = [r for r in mx_results if not r["success"]]

        if mx_succeeded:
            total_sz = sum(r["size"] for r in mx_succeeded)
            st.success(
                f"Rendered {len(mx_succeeded)} file(s) in {mx_elapsed:.1f}s. "
                f"Total output: {engine.format_bytes(total_sz)}"
                + (f" · {len(mx_skipped)} skipped (already existed)." if mx_skipped else "")
            )
        elif mx_skipped:
            st.info(f"All {len(mx_skipped)} file(s) already existed — nothing re-rendered.")
        if mx_failed:
            st.error(f"{len(mx_failed)} render(s) failed.")

        for r in mx_results:
            if not r["success"]:
                st.write(f"❌ **{r['label']}** — {r['error']}")
                continue
            _icon = "⏭" if r.get("skipped") else "✅"
            _note = " *(skipped — already existed)*" if r.get("skipped") else ""
            st.write(f"{_icon} **{r['label']}** — {engine.format_bytes(r['size'])}{_note}")
            st.code(os.path.abspath(r["path"]))
            if r["size"] <= BROWSER_DOWNLOAD_LIMIT_BYTES:
                with open(r["path"], "rb") as f:
                    st.download_button(
                        f"Download {os.path.basename(r['path'])}",
                        data=f,
                        file_name=os.path.basename(r["path"]),
                        mime=_video_mime(r["path"]),
                        key=f"mx_dl_{r['path']}",
                    )
            else:
                st.info(
                    f"Exceeds the in-browser download limit ({engine.format_bytes(BROWSER_DOWNLOAD_LIMIT_BYTES)}). "
                    "Grab it directly from the path above."
                )


# ══════════════════════════════════════════════════════════════════════════════════════════
# TAB 3 — Watch folder daemon
# ══════════════════════════════════════════════════════════════════════════════════════════

# Fragment auto-refreshes every 3 s without re-running the full script,
# so interacting with Single clip / Matrix tabs stays responsive while the
# watcher is active.
@st.fragment(run_every="3s")
def _wt_live_panel() -> None:
    watching = watch_engine.is_watching()
    cfg = watch_engine.active_config()

    if watching and cfg:
        h, rem = divmod(cfg.target_seconds, 3600)
        m, s = divmod(rem, 60)
        dur_str = f"{h}h {m}m {s}s" if h else (f"{m}m {s}s" if m else f"{s}s")
        st.success(
            f"🟢 Watching **{cfg.watch_dir}**  ·  target {dur_str}  ·  "
            f"**{watch_engine.files_processed()}** file(s) done"
        )
    else:
        st.info("⚫ Watcher is not running.")

    log = watch_engine.get_log()
    if log:
        lc1, _ = st.columns([1, 5])
        if lc1.button("Clear log", key="wt_clear"):
            watch_engine.clear_log()
            st.rerun()

        ICON = {"info": "ℹ️", "processing": "⏳", "done": "✅", "error": "❌", "skipped": "⚠️"}
        for entry in reversed(log):
            icon = ICON.get(entry.status, "•")
            detail = f"  —  {entry.detail}" if entry.detail else ""
            st.write(f"`{entry.timestamp}` {icon} **{entry.filename}**{detail}")


with tab_watch:
    st.caption(
        "Drop video files into a watched folder and they render automatically "
        "with the configured settings — runs as a background daemon while the app is open."
    )

    _watching = watch_engine.is_watching()
    _cfg = watch_engine.active_config()

    # ── 1. Configuration (locked while daemon is running) ─────────────────────
    st.subheader("1. Configuration")

    wt_watch_dir = st.text_input(
        "Watch folder (input)",
        value=_cfg.watch_dir if _cfg else os.path.abspath("watch_input"),
        disabled=_watching,
        help="New video files dropped here are picked up and rendered automatically.",
    )
    wt_out_dir = st.text_input(
        "Output folder",
        value=_cfg.output_dir if _cfg else os.path.abspath(OUTPUT_DIR),
        disabled=_watching,
        help="Rendered files land here.",
    )

    wt_d1, wt_d2, wt_d3 = st.columns(3)
    wt_hours = wt_d1.number_input(
        "Hours", min_value=0, max_value=engine.MAX_TARGET_HOURS,
        value=_cfg.target_seconds // 3600 if _cfg else 10,
        step=1, disabled=_watching, key="wt_hours",
    )
    wt_mins = wt_d2.number_input(
        "Minutes", min_value=0, max_value=59,
        value=(_cfg.target_seconds % 3600) // 60 if _cfg else 0,
        step=1, disabled=_watching, key="wt_mins",
    )
    wt_secs_val = wt_d3.number_input(
        "Seconds", min_value=0, max_value=59,
        value=_cfg.target_seconds % 60 if _cfg else 0,
        step=1, disabled=_watching, key="wt_secs",
    )

    wt_target = None
    wt_dur_err = None
    try:
        wt_target = engine.compute_total_seconds(wt_hours, wt_mins, wt_secs_val)
    except engine.InvalidDurationError as e:
        wt_dur_err = str(e)
        st.warning(wt_dur_err)

    # Optional background music
    st.caption("Background music — optional. Loops independently alongside every rendered video.")
    wt_audio_file = st.file_uploader(
        "Background music (optional)",
        type=[ext.lstrip(".") for ext in sorted(engine.ALLOWED_AUDIO_EXTENSIONS)],
        disabled=_watching,
        key="wt_audio_uploader",
    )

    wt_audio_path = None
    if wt_audio_file is not None:
        try:
            wt_a_ext = engine.validate_audio_extension(wt_audio_file.name)
            if "wt_audio_tokens" not in st.session_state:
                st.session_state["wt_audio_tokens"] = {}
            wt_tk = f"{wt_audio_file.name}:{wt_audio_file.size}"
            if wt_tk not in st.session_state["wt_audio_tokens"]:
                st.session_state["wt_audio_tokens"][wt_tk] = uuid.uuid4().hex[:10]
            wt_a_saved = os.path.join(UPLOAD_DIR, f"wta_{st.session_state['wt_audio_tokens'][wt_tk]}{wt_a_ext}")
            if not os.path.exists(wt_a_saved):
                with open(wt_a_saved, "wb") as f:
                    f.write(wt_audio_file.getbuffer())
            wt_a_info = engine.probe_audio(wt_a_saved)
            wt_audio_path = wt_a_saved
            if wt_target:
                loops = wt_target / wt_a_info.duration_seconds
                st.info(
                    f"**{wt_audio_file.name}** · {_fmt_time(wt_a_info.duration_seconds)} "
                    f"({wt_a_info.duration_seconds:.1f}s)  —  will loop **{loops:.1f}×** per render."
                )
        except engine.AutoLoopError as e:
            st.error(f"Audio rejected: {e}")
            wt_audio_path = None

    # Audio settings
    wt_volume, wt_fade_in, wt_fade_out = 1.0, 0.0, 0.0
    if wt_audio_path or (_cfg and _cfg.audio_path):
        with st.expander("🔊 Audio settings", expanded=False):
            wt_volume = st.slider(
                "Volume", 0, 200, 100, step=5, format="%d%%",
                disabled=_watching, key="wt_vol",
            ) / 100.0
            wt_fa_c, wt_fo_c = st.columns(2)
            wt_fade_in = wt_fa_c.slider(
                "Fade-in", 0.0, 60.0, 0.0, step=0.5, format="%.1fs",
                disabled=_watching, key="wt_fi",
            )
            wt_fade_out = wt_fo_c.slider(
                "Fade-out", 0.0, 60.0, 0.0, step=0.5, format="%.1fs",
                disabled=_watching, key="wt_fo",
            )
            if wt_target and (wt_fade_in + wt_fade_out) >= wt_target:
                st.warning(f"Fade total ({wt_fade_in + wt_fade_out:.1f}s) exceeds target ({wt_target}s).")

    wt_poll = st.select_slider(
        "Poll interval",
        options=[2, 5, 10, 30, 60],
        value=int(_cfg.poll_interval) if _cfg else 5,
        format_func=lambda v: f"{v}s",
        disabled=_watching,
        key="wt_poll",
    )

    # Aspect ratio
    wt_ar_id = st.radio(
        "Output aspect ratio",
        options=list(engine.ASPECT_RATIOS.keys()),
        format_func=lambda x: engine.ASPECT_RATIOS[x].label,
        horizontal=True,
        disabled=_watching,
        key="wt_ar_preset",
    )
    st.caption(engine.ASPECT_RATIOS[wt_ar_id].description)

    # Burn-in overlay
    wt_wm_text = ""
    wt_wm_text_pos = "bottom_right"
    wt_wm_text_size = 36
    wt_wm_text_color = "#FFFFFF"
    wt_wm_text_opacity = 0.9
    wt_wm_text_box = True
    wt_wm_box_color = "#000000"
    wt_wm_box_opacity = 0.4
    wt_wm_logo_saved_path = None
    wt_wm_logo_pos = "top_right"
    wt_wm_logo_width = 15
    wt_wm_logo_opacity = 0.9
    wt_wm_margin = 20

    wt_wm_enabled = st.checkbox(
        "🔖 Burn-in overlay — embed text or logo into every output frame",
        disabled=_watching,
        key="wt_wm_enabled",
    )

    if wt_wm_enabled:
        _wt_wm_positions = list(engine.OVERLAY_POSITIONS.keys())
        _wt_wm_tab_text, _wt_wm_tab_logo = st.tabs(["📝 Text", "🖼 Logo"])

        with _wt_wm_tab_text:
            wt_wm_text = st.text_input("Text content", placeholder="Channel Name · © 2025", disabled=_watching, key="wt_wm_text")
            _wtt_pc, _wtt_sc = st.columns(2)
            wt_wm_text_pos = _wtt_pc.selectbox(
                "Position", options=_wt_wm_positions,
                format_func=lambda x: engine.OVERLAY_POSITIONS[x],
                index=_wt_wm_positions.index("bottom_right"), disabled=_watching, key="wt_wm_text_pos",
            )
            wt_wm_text_size = _wtt_sc.slider("Font size (px)", 12, 120, 36, step=4, disabled=_watching, key="wt_wm_text_size")
            _wtt_cc, _wtt_oc = st.columns(2)
            wt_wm_text_color = _wtt_cc.color_picker("Text color", "#FFFFFF", key="wt_wm_text_color")
            wt_wm_text_opacity = _wtt_oc.slider("Text opacity", 0.1, 1.0, 0.9, step=0.05, disabled=_watching, key="wt_wm_text_opacity")
            wt_wm_text_box = st.checkbox("Background box", value=True, disabled=_watching, key="wt_wm_text_box")
            if wt_wm_text_box:
                _wtt_bcc, _wtt_boc = st.columns(2)
                wt_wm_box_color = _wtt_bcc.color_picker("Box color", "#000000", key="wt_wm_box_color")
                wt_wm_box_opacity = _wtt_boc.slider("Box opacity", 0.1, 1.0, 0.4, step=0.05, disabled=_watching, key="wt_wm_box_opacity")

        with _wt_wm_tab_logo:
            wt_wm_logo_file = st.file_uploader(
                "Logo / watermark image (PNG recommended)",
                type=["png", "jpg", "jpeg", "webp"], disabled=_watching, key="wt_wm_logo_uploader",
            )
            if wt_wm_logo_file is not None:
                if "wt_wm_logo_tokens" not in st.session_state:
                    st.session_state["wt_wm_logo_tokens"] = {}
                _wtwml_tk = f"{wt_wm_logo_file.name}:{wt_wm_logo_file.size}"
                if _wtwml_tk not in st.session_state["wt_wm_logo_tokens"]:
                    st.session_state["wt_wm_logo_tokens"][_wtwml_tk] = uuid.uuid4().hex[:10]
                _wtwml_ext = os.path.splitext(wt_wm_logo_file.name)[1].lower()
                wt_wm_logo_saved_path = os.path.join(
                    UPLOAD_DIR,
                    f"wtwml_{st.session_state['wt_wm_logo_tokens'][_wtwml_tk]}{_wtwml_ext}",
                )
                if not os.path.exists(wt_wm_logo_saved_path):
                    with open(wt_wm_logo_saved_path, "wb") as _f:
                        _f.write(wt_wm_logo_file.getbuffer())
            _wtl_pc, _wtl_sc = st.columns(2)
            wt_wm_logo_pos = _wtl_pc.selectbox(
                "Position", options=_wt_wm_positions,
                format_func=lambda x: engine.OVERLAY_POSITIONS[x],
                index=_wt_wm_positions.index("top_right"), disabled=_watching, key="wt_wm_logo_pos",
            )
            wt_wm_logo_width = _wtl_sc.slider("Logo width (% of frame)", 5, 50, 15, step=5, disabled=_watching, key="wt_wm_logo_width")
            wt_wm_logo_opacity = st.slider("Logo opacity", 0.1, 1.0, 0.9, step=0.05, disabled=_watching, key="wt_wm_logo_opacity")

        wt_wm_margin = st.slider("Edge margin (px)", 0, 60, 20, step=4, disabled=_watching, key="wt_wm_margin")

    _wt_wm_cfg = engine.WatermarkConfig(
        text=wt_wm_text, text_position=wt_wm_text_pos, text_size=wt_wm_text_size,
        text_color=wt_wm_text_color, text_opacity=wt_wm_text_opacity,
        text_box=wt_wm_text_box, text_box_color=wt_wm_box_color, text_box_opacity=wt_wm_box_opacity,
        logo_path=wt_wm_logo_saved_path, logo_position=wt_wm_logo_pos,
        logo_width_pct=wt_wm_logo_width, logo_opacity=wt_wm_logo_opacity, margin=wt_wm_margin,
    )

    # Output format
    wt_preset_id = st.radio(
        "Output format",
        options=list(engine.ENCODE_PRESETS.keys()),
        format_func=lambda x: engine.ENCODE_PRESETS[x].label,
        horizontal=True,
        disabled=_watching,
        key="wt_enc_preset",
    )
    wt_sel_preset = engine.ENCODE_PRESETS[wt_preset_id]
    _wt_c1, _wt_c2, _wt_c3 = st.columns(3)
    _wt_c1.metric("Encode speed", wt_sel_preset.speed_label)
    _wt_c2.metric("File size", wt_sel_preset.size_label)
    _wt_c3.metric("Compatibility", wt_sel_preset.compat_label)
    st.caption(wt_sel_preset.description)

    wt_enc_crf: int | None = None
    if wt_preset_id == "h264":
        _wt_h264_ql = st.select_slider(
            "H.264 quality",
            options=["Smaller file (CRF 28)", "Balanced (CRF 23)", "High quality (CRF 18)"],
            value="Balanced (CRF 23)",
            disabled=_watching,
            key="wt_enc_crf_h264",
        )
        wt_enc_crf = {"Smaller file (CRF 28)": 28, "Balanced (CRF 23)": 23, "High quality (CRF 18)": 18}[_wt_h264_ql]
    elif wt_preset_id == "h265":
        _wt_h265_ql = st.select_slider(
            "H.265 quality",
            options=["Smaller file (CRF 32)", "Balanced (CRF 28)", "High quality (CRF 24)"],
            value="Balanced (CRF 28)",
            disabled=_watching,
            key="wt_enc_crf_h265",
        )
        wt_enc_crf = {"Smaller file (CRF 32)": 32, "Balanced (CRF 28)": 28, "High quality (CRF 24)": 24}[_wt_h265_ql]

    # ── 2. Start / Stop ───────────────────────────────────────────────────────
    st.subheader("2. Control")

    wt_valid = (
        bool(wt_watch_dir.strip())
        and bool(wt_out_dir.strip())
        and wt_target is not None
        and wt_dur_err is None
    )

    if _watching:
        ctl1, ctl2 = st.columns([4, 1])
        ctl1.write("")  # spacer for alignment
        if ctl2.button("⏹ Stop", type="secondary", key="wt_stop"):
            watch_engine.stop_watcher()
            st.rerun()
    else:
        if st.button("▶ Start Watching", type="primary", disabled=not wt_valid, key="wt_start"):
            watch_engine.start_watcher(watch_engine.WatchConfig(
                watch_dir=wt_watch_dir.strip(),
                output_dir=wt_out_dir.strip(),
                target_seconds=wt_target,
                audio_path=wt_audio_path,
                volume=wt_volume,
                fade_in=wt_fade_in,
                fade_out=wt_fade_out,
                poll_interval=float(wt_poll),
                ar_id=wt_ar_id,
                watermark=_wt_wm_cfg if _wt_wm_cfg.is_active else None,
                preset_id=wt_preset_id,
                enc_crf=wt_enc_crf,
            ))
            st.rerun()

    # ── 3. Live status + log (auto-refreshes via @st.fragment) ───────────────
    st.subheader("3. Activity")
    _wt_live_panel()


# ══════════════════════════════════════════════════════════════════════════════════════════
# TAB 4 — Render history
# ══════════════════════════════════════════════════════════════════════════════════════════

def _fmt_dur(seconds: float) -> str:
    h, rem = divmod(int(seconds), 3600)
    m, s = divmod(rem, 60)
    if h:
        return f"{h}h {m}m {s}s"
    if m:
        return f"{m}m {s}s"
    return f"{s}s"


with tab_history:
    st.caption(
        "All renders logged here — delete output files to reclaim disk space "
        "without leaving the app."
    )

    _hist = job_history.load_history()
    _hist_exists = [r for r in _hist if os.path.exists(r.output_path)]
    _hist_missing = [r for r in _hist if not os.path.exists(r.output_path)]
    _on_disk_bytes = sum(os.path.getsize(r.output_path) for r in _hist_exists)

    # ── Stats bar ──────────────────────────────────────────────────────────────
    _hs1, _hs2, _hs3, _hs4 = st.columns(4)
    _hs1.metric("Total renders", len(_hist))
    _hs2.metric("Files on disk", len(_hist_exists))
    _hs3.metric("Disk used", engine.format_bytes(_on_disk_bytes) if _hist_exists else "0 B")
    _hs4.metric("Missing files", len(_hist_missing))

    # ── Bulk actions ───────────────────────────────────────────────────────────
    _hb1, _hb2, _hb3 = st.columns([2, 2, 3])
    if _hb1.button("Remove missing entries", disabled=not _hist_missing, key="hist_clear_missing"):
        n = job_history.remove_missing()
        st.success(f"Removed {n} missing entr{'y' if n == 1 else 'ies'}.")
        st.rerun()
    if _hb2.button("Clear all history", type="secondary", key="hist_clear_all"):
        job_history.clear_history()
        st.rerun()

    if not _hist:
        st.info("No renders recorded yet. Run a render in Single clip, Matrix, or Watch folder to see history here.")
        st.stop()

    st.divider()

    # ── Filter ─────────────────────────────────────────────────────────────────
    _hf1, _hf2 = st.columns([3, 2])
    _hist_filter = _hf1.selectbox(
        "Show",
        options=["All", "On disk", "Missing", "Single clip", "Matrix", "Watch folder"],
        index=0, key="hist_filter",
    )
    _hist_search = _hf2.text_input("Search label / file", placeholder="clip.mp4", key="hist_search")

    _filter_map = {"All": None, "On disk": "exists", "Missing": "missing",
                   "Single clip": "single", "Matrix": "matrix", "Watch folder": "watch"}
    _fmode = _filter_map[_hist_filter]

    _hist_view = _hist
    if _fmode == "exists":
        _hist_view = _hist_exists
    elif _fmode == "missing":
        _hist_view = _hist_missing
    elif _fmode in ("single", "matrix", "watch"):
        _hist_view = [r for r in _hist if r.tab == _fmode]
    if _hist_search.strip():
        _q = _hist_search.strip().lower()
        _hist_view = [r for r in _hist_view if _q in r.label.lower() or _q in r.source_file.lower()]

    if not _hist_view:
        st.info("No records match the current filter.")
    else:
        st.caption(f"Showing **{len(_hist_view)}** record(s)")

    # ── Record list ────────────────────────────────────────────────────────────
    TAB_ICON = {"single": "🎬", "matrix": "⊞", "watch": "👁"}
    PRESET_LABEL = {p: engine.ENCODE_PRESETS[p].label for p in engine.ENCODE_PRESETS}

    for rec in _hist_view:
        _file_exists = os.path.exists(rec.output_path)
        _border_color = "green" if _file_exists else "gray"

        with st.container(border=True):
            _rc1, _rc2 = st.columns([7, 3])

            with _rc1:
                _tab_icon = TAB_ICON.get(rec.tab, "•")
                _preset_lbl = PRESET_LABEL.get(rec.preset_id, rec.preset_id)
                _ar_lbl = engine.ASPECT_RATIOS[rec.ar_id].label if rec.ar_id in engine.ASPECT_RATIOS else rec.ar_id
                _exists_badge = "✅" if _file_exists else "⚠️ *missing*"

                st.markdown(
                    f"{_tab_icon} **{rec.label}** &nbsp; {_exists_badge}  \n"
                    f"`{rec.timestamp}` · {_fmt_dur(rec.duration_seconds)} · "
                    f"{engine.format_bytes(rec.size_bytes)} · {_preset_lbl} · {_ar_lbl}"
                )
                _abs_path = os.path.abspath(rec.output_path)
                st.code(_abs_path, language=None)

            with _rc2:
                if _file_exists:
                    if st.button(
                        "🗑 Delete file", key=f"hist_del_{rec.id}",
                        help="Delete this output file from disk and remove the history entry.",
                        use_container_width=True,
                    ):
                        try:
                            os.remove(rec.output_path)
                        except OSError as _e:
                            st.error(f"Could not delete: {_e}")
                        job_history.remove_job(rec.id)
                        st.rerun()

                    if rec.size_bytes <= BROWSER_DOWNLOAD_LIMIT_BYTES:
                        with open(rec.output_path, "rb") as _f:
                            st.download_button(
                                "⬇ Download",
                                data=_f,
                                file_name=os.path.basename(rec.output_path),
                                mime=_video_mime(rec.output_path),
                                key=f"hist_dl_{rec.id}",
                                use_container_width=True,
                            )
                else:
                    st.button(
                        "🗑 Delete file", key=f"hist_del_{rec.id}", disabled=True,
                        help="File no longer exists on disk.",
                        use_container_width=True,
                    )

                if st.button(
                    "✕ Remove entry", key=f"hist_rm_{rec.id}",
                    help="Remove this entry from history without touching the file.",
                    use_container_width=True,
                ):
                    job_history.remove_job(rec.id)
                    st.rerun()
